
services:
  # NGINX Service
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    volumes:
      - ./backups:/var/www/backups
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge