server {
  listen 80;
  server_name docker-baas.localhost;
  root /var/www/backups; 

  auth_basic "Restricted Access - Backups";
  auth_basic_user_file /etc/nginx/conf.d/.htpasswd;

  # Позволява да виждаш списъка с папки и файлове в браузъра
  autoindex on;
  autoindex_exact_size off;
  autoindex_localtime on;

  location / {
    try_files $uri $uri/ =404;
  }
}